### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by YuchengWang** [androidthings/sample-tensorflow-imageclassifier#3]
using android studio 2.3, windows 10, 64bit

Error:(4, 0) Declaring custom 'clean' task when using the standard Gradle lifecycle plugins is not allowed.
<a href="openFile:D:\code\android-things\code\sample-tensorflow-imageclassifier-master\app\build.gradle">Open File</a>

Gradle sync failed: Declaring custom 'clean' task when using the standard Gradle lifecycle plugins is not allowed.
		Consult IDE log for more details (Help | Show Log)

**Comment by YuchengWang** [comment]
[idea.zip](https://github.com/androidthings/sample-tensorflow-imageclassifier/files/855252/idea.zip)

the below is log

**Comment by binnykmathew** [comment]
I got the same error but was able to successfully build and also deploy after I commented out the following line from the build.gradle file

/*    task clean(type: Delete) {
        delete rootProject.buildDir
    } */

**Comment by tiagoalexbastos** [comment]
thanks @binnykmathew , solved with the comment.

**Comment by tanishq-rocks** [comment]
/* task clean(type: Delete) {
delete rootProject.buildDir
} */
comment like this..
and then follow the instruction and it will start to download some files & gradle built successfully after sometime.it takes 3-4minute.

**Comment by Fleker** [comment]
Are you still seeing this issue? I have not had any issues with using Gradle and the latest (3.1+) versions of Android Studio. I'll close this soon if there's no further issue.
